// board-mad Zod parameter schema. Extracted from index.ts so that sweep.ts
// can reference `Params` (for its `Omit<Params,'kMad'>` argument type) without
// importing index.ts, which in turn imports sweep.ts.

import { z } from "zod";

import {
  BOARD_MAD_BASELINE_MODE_DEFAULT,
  BOARD_MAD_BASELINE_MODE_HISTORICAL_BLEND,
  BOARD_MAD_BASELINE_MODE_OPENING_RAMP,
  BOARD_MAD_BASELINE_MODE_TRAILING,
  BOARD_MAD_BUCKET_SECONDS_DEFAULT,
  BOARD_MAD_BUCKET_SECONDS_MAX,
  BOARD_MAD_BUCKET_SECONDS_MIN,
  BOARD_MAD_FRESH_CAP_SECONDS_DEFAULT,
  BOARD_MAD_FRESH_CAP_SECONDS_MAX,
  BOARD_MAD_FRESH_CAP_SECONDS_MIN,
  BOARD_MAD_HISTORICAL_AWAY_WEIGHT_DEFAULT,
  BOARD_MAD_HISTORICAL_AWAY_WEIGHT_MAX,
  BOARD_MAD_HISTORICAL_AWAY_WEIGHT_MIN,
  BOARD_MAD_HISTORICAL_LAST_GAMES_DEFAULT,
  BOARD_MAD_HISTORICAL_LAST_GAMES_MAX,
  BOARD_MAD_HISTORICAL_LAST_GAMES_MIN,
  BOARD_MAD_HISTORICAL_PRIOR_WEIGHT_DEFAULT,
  BOARD_MAD_HISTORICAL_PRIOR_WEIGHT_MAX,
  BOARD_MAD_HISTORICAL_PRIOR_WEIGHT_MIN,
  BOARD_MAD_HISTORICAL_RAMP_COMPLETE_GAME_MINUTES_DEFAULT,
  BOARD_MAD_HISTORICAL_RAMP_COMPLETE_GAME_MINUTES_MAX,
  BOARD_MAD_HISTORICAL_RAMP_COMPLETE_GAME_MINUTES_MIN,
  BOARD_MAD_K_MAD_MAX,
  BOARD_MAD_K_MAD_MIN,
  BOARD_MAD_OPENING_BASELINE_BUCKETS_DEFAULT,
  BOARD_MAD_OPENING_BASELINE_BUCKETS_MAX,
  BOARD_MAD_OPENING_BASELINE_BUCKETS_MIN,
  BOARD_MAD_RECENT_WALL_MINUTES_DEFAULT,
  BOARD_MAD_RECENT_WALL_MINUTES_MAX,
  BOARD_MAD_RECENT_WALL_MINUTES_MIN,
  BOARD_MAD_RECENT_WALL_WEIGHT_DEFAULT,
  BOARD_MAD_RECENT_WALL_WEIGHT_MAX,
  BOARD_MAD_RECENT_WALL_WEIGHT_MIN,
  BOARD_MAD_TRAILING_GAME_MINUTES_DEFAULT,
  BOARD_MAD_TRAILING_GAME_MINUTES_MAX,
  BOARD_MAD_TRAILING_GAME_MINUTES_MIN,
  BOARD_MAD_OPENING_RAMP_COMPLETE_BUCKETS_DEFAULT,
  BOARD_MAD_OPENING_RAMP_COMPLETE_BUCKETS_MAX,
  BOARD_MAD_OPENING_RAMP_COMPLETE_BUCKETS_MIN,
  BOARD_MAD_TRAILING_BUCKETS_DEFAULT,
  BOARD_MAD_TRAILING_BUCKETS_MAX,
  BOARD_MAD_TRAILING_BUCKETS_MIN,
  BOARD_MAD_WARMUP_BUCKETS_DEFAULT,
  BOARD_MAD_WARMUP_BUCKETS_MAX,
  BOARD_MAD_WARMUP_BUCKETS_MIN,
  BOARD_MAD_WEIGHTING_DEFAULT,
  K_MAD_LIVE,
} from "./config";
import {
  BOARD_STATE_SPACE_CONFIG_DEFAULTS,
  BoardStateSpaceConfigSchema,
} from "./state-space-config";

export const Params = z.object({
  bucketSeconds: z
    .number()
    .int()
    .min(BOARD_MAD_BUCKET_SECONDS_MIN)
    .max(BOARD_MAD_BUCKET_SECONDS_MAX)
    .default(BOARD_MAD_BUCKET_SECONDS_DEFAULT),
  kMad: z.number().min(BOARD_MAD_K_MAD_MIN).max(BOARD_MAD_K_MAD_MAX).default(K_MAD_LIVE),
  weighting: z.enum(["volume", "equal"]).default(BOARD_MAD_WEIGHTING_DEFAULT),
  trailingBuckets: z
    .number()
    .int()
    .min(BOARD_MAD_TRAILING_BUCKETS_MIN)
    .max(BOARD_MAD_TRAILING_BUCKETS_MAX)
    .default(BOARD_MAD_TRAILING_BUCKETS_DEFAULT),
  warmupBuckets: z
    .number()
    .int()
    .min(BOARD_MAD_WARMUP_BUCKETS_MIN)
    .max(BOARD_MAD_WARMUP_BUCKETS_MAX)
    .default(BOARD_MAD_WARMUP_BUCKETS_DEFAULT),
  baselineMode: z
    .enum([
      BOARD_MAD_BASELINE_MODE_TRAILING,
      BOARD_MAD_BASELINE_MODE_OPENING_RAMP,
      BOARD_MAD_BASELINE_MODE_HISTORICAL_BLEND,
    ])
    .default(BOARD_MAD_BASELINE_MODE_DEFAULT),
  openingBaselineBuckets: z
    .number()
    .int()
    .min(BOARD_MAD_OPENING_BASELINE_BUCKETS_MIN)
    .max(BOARD_MAD_OPENING_BASELINE_BUCKETS_MAX)
    .default(BOARD_MAD_OPENING_BASELINE_BUCKETS_DEFAULT),
  openingRampCompleteBuckets: z
    .number()
    .int()
    .min(BOARD_MAD_OPENING_RAMP_COMPLETE_BUCKETS_MIN)
    .max(BOARD_MAD_OPENING_RAMP_COMPLETE_BUCKETS_MAX)
    .default(BOARD_MAD_OPENING_RAMP_COMPLETE_BUCKETS_DEFAULT),
  historicalLastGames: z
    .number()
    .int()
    .min(BOARD_MAD_HISTORICAL_LAST_GAMES_MIN)
    .max(BOARD_MAD_HISTORICAL_LAST_GAMES_MAX)
    .default(BOARD_MAD_HISTORICAL_LAST_GAMES_DEFAULT),
  historicalPriorWeight: z
    .number()
    .min(BOARD_MAD_HISTORICAL_PRIOR_WEIGHT_MIN)
    .max(BOARD_MAD_HISTORICAL_PRIOR_WEIGHT_MAX)
    .default(BOARD_MAD_HISTORICAL_PRIOR_WEIGHT_DEFAULT),
  historicalAwayWeight: z
    .number()
    .min(BOARD_MAD_HISTORICAL_AWAY_WEIGHT_MIN)
    .max(BOARD_MAD_HISTORICAL_AWAY_WEIGHT_MAX)
    .default(BOARD_MAD_HISTORICAL_AWAY_WEIGHT_DEFAULT),
  historicalRampCompleteGameMinutes: z
    .number()
    .min(BOARD_MAD_HISTORICAL_RAMP_COMPLETE_GAME_MINUTES_MIN)
    .max(BOARD_MAD_HISTORICAL_RAMP_COMPLETE_GAME_MINUTES_MAX)
    .default(BOARD_MAD_HISTORICAL_RAMP_COMPLETE_GAME_MINUTES_DEFAULT),
  trailingGameMinutes: z
    .number()
    .min(BOARD_MAD_TRAILING_GAME_MINUTES_MIN)
    .max(BOARD_MAD_TRAILING_GAME_MINUTES_MAX)
    .default(BOARD_MAD_TRAILING_GAME_MINUTES_DEFAULT),
  recentWallMinutes: z
    .number()
    .min(BOARD_MAD_RECENT_WALL_MINUTES_MIN)
    .max(BOARD_MAD_RECENT_WALL_MINUTES_MAX)
    .default(BOARD_MAD_RECENT_WALL_MINUTES_DEFAULT),
  recentWallWeight: z
    .number()
    .min(BOARD_MAD_RECENT_WALL_WEIGHT_MIN)
    .max(BOARD_MAD_RECENT_WALL_WEIGHT_MAX)
    .default(BOARD_MAD_RECENT_WALL_WEIGHT_DEFAULT),
  freshCapSeconds: z
    .number()
    .int()
    .min(BOARD_MAD_FRESH_CAP_SECONDS_MIN)
    .max(BOARD_MAD_FRESH_CAP_SECONDS_MAX)
    .default(BOARD_MAD_FRESH_CAP_SECONDS_DEFAULT),
  stateSpace: BoardStateSpaceConfigSchema.default(BOARD_STATE_SPACE_CONFIG_DEFAULTS),
});

export type ParamsResolved = z.infer<typeof Params>;
export type Weighting = ParamsResolved["weighting"];
