"""``bootstrap`` subcommand: emit a runnable quant-lab starter notebook.

This writes ``notebooks/quant-lab-starter.ipynb`` (relative to the repo root by
default) as a small, end-to-end-runnable tour of the research contract:

1. import pandas / duckdb (and the in-repo loader + robust_mad model),
2. open an exported snapshot directory,
3. load ``board_observations`` into a DataFrame,
4. pick one game present in BOTH board_observations and incidents, then plot
   that game's ``intensity`` with a vertical marker at its incident's
   ``utc_time`` (matplotlib, Agg backend so it runs headless),
5. run ``robust_mad`` over that game and print the fired buckets.

The notebook is built with ``nbformat`` (not hand-written JSON) and is designed
to execute cleanly under ``jupyter nbconvert --execute`` against an existing
snapshot such as
``outputs/nba-quant-lab/snapshots/sample-fixed``.
"""

from __future__ import annotations

from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

# Resolve the repo root from this file: research/cli/bootstrap.py ->
# .../apps/nba-sidecar/src/nba_sidecar/research/cli/ ; the repo root is six
# parents up (cli -> research -> nba_sidecar -> src -> nba-sidecar -> apps -> root).
_REPO_ROOT = Path(__file__).resolve().parents[6]
DEFAULT_NOTEBOOK_PATH = _REPO_ROOT / "notebooks" / "quant-lab-starter.ipynb"
DEFAULT_SNAPSHOT_PATH = (
    _REPO_ROOT / "outputs" / "nba-quant-lab" / "snapshots" / "sample-fixed"
)


def _intro_md() -> str:
    return (
        "# Quant-Lab Starter\n"
        "\n"
        "Generated by `python -m nba_sidecar.research bootstrap`.\n"
        "\n"
        "A minimal, runnable tour of the research snapshot contract:\n"
        "open a snapshot, load `board_observations`, plot one game's market\n"
        "`intensity` with its misattribution-incident marker, and run the\n"
        "`robust_mad` incumbent baseline over that game.\n"
        "\n"
        "The predictions a model emits are validated against the same\n"
        "`PREDICTION_COLUMNS` contract an external producer must satisfy\n"
        "(`game_id, bucket_start, score, fired`) — see `scripts/quant-lab-starter.R`\n"
        "and `pnpm quant score-predictions`."
    )


def _setup_code(snapshot_path: Path) -> str:
    # Use a repr'd absolute path so the notebook is runnable from any cwd.
    return (
        "# Prefer the inline backend so figures embed in the notebook (and under\n"
        "# `nbconvert --execute`); fall back to the headless Agg backend if there\n"
        "# is no IPython display (e.g. running the cells as a plain script).\n"
        "try:\n"
        "    get_ipython().run_line_magic(\"matplotlib\", \"inline\")  # type: ignore[name-defined]\n"
        "except Exception:  # noqa: BLE001 - no IPython display: use a headless backend\n"
        "    import matplotlib\n"
        "    matplotlib.use(\"Agg\")\n"
        "\n"
        "from pathlib import Path\n"
        "\n"
        "import duckdb  # noqa: F401  (proves the duckdb backend is importable)\n"
        "import matplotlib.pyplot as plt\n"
        "import pandas as pd\n"
        "\n"
        "from nba_sidecar.research.loader import build_game_series, read_board_observations\n"
        "from nba_sidecar.research.models import get_model\n"
        "from nba_sidecar.research.models.base import ScoreRequest\n"
        "\n"
        f"SNAPSHOT = Path(r\"{snapshot_path}\")\n"
        "assert SNAPSHOT.exists(), f\"snapshot dir not found: {SNAPSHOT}\"\n"
        "print(\"snapshot:\", SNAPSHOT)"
    )


_LOAD_CODE = (
    "# Load + validate board_observations (the causal model input table).\n"
    "board = read_board_observations(SNAPSHOT)\n"
    "incidents = pd.read_parquet(SNAPSHOT / \"incidents.parquet\")\n"
    "print(\"board_observations:\", board.shape)\n"
    "print(\"games:\", board[\"game_id\"].nunique(), \"| incident rows:\", len(incidents))\n"
    "board.head()"
)


_PICK_GAME_CODE = (
    "# Pick one game present in BOTH board_observations and incidents so the\n"
    "# plot below always has an incident marker to draw.\n"
    "labelled = incidents.dropna(subset=[\"canonical_game_id\"])\n"
    "common = sorted(set(board[\"game_id\"]) & set(labelled[\"canonical_game_id\"]))\n"
    "assert common, \"no game has both board_observations and an incident\"\n"
    "GAME_ID = common[0]\n"
    "game = board[board[\"game_id\"] == GAME_ID].copy()\n"
    "game[\"bucket_start\"] = pd.to_datetime(game[\"bucket_start\"], utc=True)\n"
    "game = game.sort_values(\"bucket_start\")\n"
    "game_incidents = labelled[labelled[\"canonical_game_id\"] == GAME_ID]\n"
    "print(\"chosen game:\", GAME_ID, \"| buckets:\", len(game), \"| incidents:\", len(game_incidents))"
)


_PLOT_CODE = (
    "# Plot the game's market intensity over time with a marker at each\n"
    "# incident's label time (utc_time).\n"
    "fig, ax = plt.subplots(figsize=(11, 4))\n"
    "ax.plot(game[\"bucket_start\"], game[\"intensity\"], lw=1.2, label=\"intensity\")\n"
    "for _, row in game_incidents.iterrows():\n"
    "    t = row.get(\"utc_time\")\n"
    "    if pd.isna(t):\n"
    "        continue\n"
    "    ax.axvline(pd.to_datetime(t, utc=True), color=\"crimson\", ls=\"--\", lw=1.5,\n"
    "               label=f\"incident {row['incident_id']}\")\n"
    "ax.set_title(f\"Board intensity + incident marker — {GAME_ID}\")\n"
    "ax.set_xlabel(\"bucket_start (UTC)\")\n"
    "ax.set_ylabel(\"intensity\")\n"
    "ax.legend(loc=\"upper left\", fontsize=8)\n"
    "fig.autofmt_xdate()\n"
    "fig.tight_layout()\n"
    "fig"
)


_MODEL_CODE = (
    "# Run the robust_mad incumbent baseline over the chosen game and print fires.\n"
    "series_by_game = build_game_series(board)\n"
    "model = get_model(\"robust_mad\")\n"
    "result = model.score(ScoreRequest(series=series_by_game[GAME_ID], params={}))\n"
    "fired = [p for p in result.predictions if p.fired]\n"
    "print(f\"robust_mad fired {len(fired)} / {len(result.predictions)} buckets for {GAME_ID}\")\n"
    "for p in fired[:10]:\n"
    "    print(f\"  {p.bucket_start.isoformat()}  score={p.score:.2f}\")\n"
    "if len(fired) > 10:\n"
    "    print(f\"  ... and {len(fired) - 10} more\")"
)


def build_notebook(snapshot_path: Path) -> nbformat.NotebookNode:
    """Construct the starter notebook node for ``snapshot_path``."""
    nb = new_notebook()
    nb.cells = [
        new_markdown_cell(_intro_md()),
        new_markdown_cell("## 1. Setup: imports + open the snapshot"),
        new_code_cell(_setup_code(snapshot_path)),
        new_markdown_cell("## 2. Load board_observations + incidents"),
        new_code_cell(_LOAD_CODE),
        new_markdown_cell("## 3. Pick a game with an incident"),
        new_code_cell(_PICK_GAME_CODE),
        new_markdown_cell("## 4. Plot intensity with the incident marker"),
        new_code_cell(_PLOT_CODE),
        new_markdown_cell("## 5. Run robust_mad and print fires"),
        new_code_cell(_MODEL_CODE),
    ]
    # Pin a concrete kernelspec so `nbconvert --execute` resolves the venv kernel.
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb.metadata["language_info"] = {"name": "python"}
    return nb


def write_notebook(
    *, notebook_path: Path | None = None, snapshot_path: Path | None = None
) -> Path:
    """Write the starter notebook to disk; return the path written."""
    out = notebook_path or DEFAULT_NOTEBOOK_PATH
    snap = snapshot_path or DEFAULT_SNAPSHOT_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    nb = build_notebook(snap)
    nbformat.write(nb, str(out))
    return out


__all__ = [
    "DEFAULT_NOTEBOOK_PATH",
    "DEFAULT_SNAPSHOT_PATH",
    "build_notebook",
    "write_notebook",
]
